spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionPannes?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    enabled: true
    check-template-location: true
    cache: false

server:
  port: 8082